layout_spectrum: 1
color:
  saturation: 0.4608673
  brandStrength: 0.6149302
  lightness: 0.1897999
  brandColors:
    - '#0E0E0C'
    - '#807E78'
    - '#FFFFFF'
    - '#894B27'
    - '#1E89B3'
  rhythmicContrast: 0.2422899
typography_spectrum: 0.4860365
name: Testing1wureno
