name: Testing1wureno
favicon: null
layout_spectrum: 0.78615
typography_spectrum: 0.35066
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0E0E0C'
    - '#807E78'
    - '#FFFFFF'
    - '#894B27'
    - '#1E89B3'
  brandStrength: 0.6149302
  lightness: 0.7502685
  saturation: 0.7180451
  rhythmicContrast: 0.632116
purpose: []
